Repository XaoGao/Todoser, pull requests merged in 2022-06, with the labels that each got.

#32 Fix #25 Add JwtService class with encoding and decoding methods
  Gemfile
  Gemfile.lock
  app/services/jwt_service.rb
  config/credentials.yml.enc
  spec/services/jwt_service_spec.rb
Labels: enhancement

#34 fix docker-compose file
  .env.example
  config/database.yml
  db/schema.rb
  docker-compose.yml
Labels: bug

#50 fix issue #48 or 15
  .gitignore
Labels: good first issue

#30 Add: #27 class Service
  app/services/service.rb
  spec/services/service_spec.rb
Labels: enhancement, good first issue

#58 fix issue #19: skip dashboard from navbar for non sign_in users
  app/views/layouts/_navbar.html.slim
Labels: bug

#83 Fix issue #82 docker compose up
  .env.example
  .github/.keep
  README.md
Labels: documentation

#86 add action policy gem issue#76
  Gemfile
  app/policies/application_policy.rb
Labels: enhancement

#90 Todoser-89: add project#show policy
  app/controllers/application_controller.rb
  app/controllers/concerns/unauthorized.rb
  app/controllers/projects_controller.rb
  app/policies/project_policy.rb
  config/locales/en.yml
  spec/policies/project_policy_spec.rb
Labels: enhancement

#84 Todoser-35: добавлен модель favorite
  app/models/favorite.rb
  app/models/user.rb
  db/migrate/20220614124540_create_favorites.rb
  db/schema.rb
  spec/factories/favorites.rb
  spec/models/favorite_spec.rb
Labels: enhancement
